name: horario_escolar
description: Horario de materias escolares.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"
  flutter_native_splash: ^0.1.9

flutter_native_splash:
  image: assets/imagenes/splash.png
  color: "F5F5F5"
  ios: false

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/launcher/icon.png"

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-SemiBold.ttf